eureka:
  client:
    service-url:
     defaultZone: http://123.207.39.91:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-helloworld
  cloud:
    config:
      label: master
      profile: dev
  datasource:
    url: jdbc:mysql://123.207.39.91:3306/test
    username: root
    password: 950419
    driver-class-name: com.mysql.jdbc.Driver