eureka:
  client:
    service-url:
     defaultZone: http://123.207.39.91:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-helloworld
  cloud:
    config:
      label: master
      profile: dev
  datasource:
    url: jdbc:mysql://123.207.39.91:3306/test?useSSL=false
    username: root
    password: 950419
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
mybatis:
  type-aliases-package: springcloud.client.entity
  mapper-locations: classpath:springcloud.client.dao.mapple/*.xml