eureka:
  client:
    service-url:
     defaultZone: http://123.207.39.91:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-helloworld
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/