package springcloud.client.dao;

import org.springframework.stereotype.Component;
import springcloud.client.entity.UserRedPacket;

/**
 * @author hezy
 */
@Component
public interface UserRedPacketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_RED_PACKET
     *
     * @mbggenerated Thu Mar 07 14:50:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_RED_PACKET
     *
     * @mbggenerated Thu Mar 07 14:50:15 CST 2019
     */
    int insert(UserRedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_RED_PACKET
     *
     * @mbggenerated Thu Mar 07 14:50:15 CST 2019
     */
    int insertSelective(UserRedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_RED_PACKET
     *
     * @mbggenerated Thu Mar 07 14:50:15 CST 2019
     */
    UserRedPacket selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_RED_PACKET
     *
     * @mbggenerated Thu Mar 07 14:50:15 CST 2019
     */
    int updateByPrimaryKeySelective(UserRedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_RED_PACKET
     *
     * @mbggenerated Thu Mar 07 14:50:15 CST 2019
     */
    int updateByPrimaryKey(UserRedPacket record);
}